test:
  user:
    info:
      name: 韩
      email: hantenghui@tuyoogame.com
      uuid: ${random.uuid}

mysql:
  url: jdbc:mysql://localhost:3306/practice?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456
  driver: com.mysql.jdbc.Driver

spring:
    datasource:
      url: jdbc:impala://biserverha.ywdier.com:21050
      driver-class-name: com.cloudera.impala.jdbc41.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 1
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
